### ISSUE TITLE
Cannot create Digi-Key list

### ISSUE THREAD

**Issue by jasonharper** [Digi-Key/KiCad-Push-to-DigiKey#1]
This seems like it would be a very useful plugin, but it fails every time I run it - the progress bar gets to about 75% full, in the "Preparing the webpage..." stage, but then I get an error popup:
> There was an error while creating a Digi-Key list from the given part numbers.
> Please try again later or contact Digi-Key at https://www.digikey.com/en/help-support

Every part number in my BOM is copied & pasted directly from the DK website, so I have no idea of what I could try to fix this.

Windows 11 computer, plugin version 1.0.4, PCB Editor version 7.0.9.

**Comment by Walseth15** [comment]
@jasonharper, thanks for pointing this out! Our team is looking into it.

**Comment by Walseth15** [comment]
@jasonharper - This has been resolved. You should now be able to re-run the plugin to pass your BOM to DigiKey.
