### ISSUE TITLE
BOM only lists the first 12 items but board has 75 items across 30 part numbers.

### ISSUE THREAD

**Issue by pedroeltoro** [Digi-Key/KiCad-Push-to-DigiKey#4]
Bill of materials is incomplete in Digikey but BOM export appears fully functional and correct when exporting CSV.

Application: KiCad Schematic Editor x86_64 on x86_64

Version: 8.0.2-34-g43d4c8d801, release build

Libraries:
	wxWidgets 3.2.4
	FreeType 2.13.2
	HarfBuzz 8.3.0
	FontConfig 2.15.0
	libcurl/8.4.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.58.0

Platform: macOS Sonoma Version 14.4.1 (Build 23E224), 64 bit, Little endian, wxMac

Build Info:
	Date: May  1 2024 06:15:06
	wxWidgets: 3.2.4 (wchar_t,wx containers)
	Boost: 1.84.0
	OCC: 7.7.2
	Curl: 7.87.0
	ngspice: 42
	Compiler: Clang 14.0.3 with C++ ABI 1002

Build settings:

**Comment by Walseth15** [comment]
@pedroeltoro - can you share more information on which parts are being excluded and if the data fields differ from the parts that are being passed to DigiKey?

**Comment by pedroeltoro** [comment]
Here's the list as pushed into myLists: https://www.digikey.co.uk/en/mylists/list/VN0OM0J9SV

Attached the exported BOM using the native KiCad tool: 
[digikey_bom_03_05_2024_BOM.csv](https://github.com/Digi-Key/KiCad-Push-to-DigiKey/files/15225403/digikey_bom_03_05_2024_BOM.csv)

**Comment by Walseth15** [comment]
I can see some part numbers in your BOM are in the Value field, but a part number field is missing from your BOM export.  When you pushed to DigiKey using the plugin, which field did you choose as your part number?  
If you open the "Edit Symbol Fileds" in the Schematic Editor, you should be able to show the field used for part numbers and get all of your part numbers to a single column.

**Comment by pedroeltoro** [comment]
Ok, I've removed the part numbers from the Value field - all the part numbers are now in "Manufacturer part number". Same issue. The list is always being cut-off at the 11th row.
<img width="1440" alt="Screenshot 2024-05-07 at 17 28 54" src="https://github.com/Digi-Key/KiCad-Push-to-DigiKey/assets/4151646/19266fc8-6bb0-41da-9937-84c64c9387e3">

**Comment by Walseth15** [comment]
Could you please provide the BOM export (CSV) with the Manufacturer part number column included so we can do some checking?

**Comment by pedroeltoro** [comment]
[digikey_bom_08_05_2024_BOM.csv](https://github.com/Digi-Key/KiCad-Push-to-DigiKey/files/15254036/digikey_bom_08_05_2024_BOM.csv)

**Comment by Walseth15** [comment]
If you're willing to share your project, that would really help in being able to reproduce the issue, or I'd be happy to setup a meeting link so we can walk through the issue live.

**Comment by taegge** [comment]
@Walseth15 to reproduce, please try to create a schematic with components inside of a hierarchical sheet. I am having a similar issue, and I noticed that the components on the top sheet feed to the plugin correctly. Components on lower level sheets appear to be ignored.

**Comment by Walseth15** [comment]
The support for parsing part numbers from hierarchical sheets has been resolved in the [latest release](https://github.com/Digi-Key/KiCad-Push-to-DigiKey/releases)
