### ISSUE TITLE
Doesn't work with multi-unit symbols

### ISSUE THREAD

**Issue by miranda** [Digi-Key/KiCad-Push-to-DigiKey#6]
Parts with multi-unit symbols don't seem to work with the plugin... I can't figure out any way to get it to see them.  For example:

kicad library symbol:
4xxx:4066
digikey part:
1727-2811-1-ND

kicad library symbol:
FPGA_Efinix_Trion:T8Q144xx
digikey part:
2134-T8Q144C4-ND

**Comment by Walseth15** [comment]
@miranda - Thank you for the feedback.  This should be resolved in the [latest release](https://github.com/Digi-Key/KiCad-Push-to-DigiKey/releases).
